version: '3.9'

services:
  evaluasiosv3_app:
    build:
      context: .
      dockerfile: Dockerfile

    image: kmz_evaluasiosv3:latest

    container_name: kmz_evaluasiosv3

    restart: unless-stopped

    networks:
      - app-network

    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://10.1.53.220:8007
      APP_KEY: base64:bQXhlf4lMqXKMZXwGUzrEe0lAs3qYNkW/Cz1Q161378=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: SWP_evaluasi_os_v3
      DB_USERNAME: UserKmzOs
      DB_PASSWORD: 'App08062026$$_'

    volumes:
      - public_data:/var/www/public

volumes:
  public_data:
    name: evaluasiosv3_public

networks:
  app-network:
    external: true
