services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: evaluasios
    container_name: evaluasios-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8004:8080"

  scheduler:
    image: evaluasios
    container_name: evaluasios-scheduler
    restart: unless-stopped
    working_dir: /var/www/
